### ISSUE TITLE
Define linelist object

### ISSUE THREAD

**Issue by zkamvar** [reconhub/linelist#2]
This object should define both associated metadata and a data dictionary. This could be based on the hxl tags: http://hxlstandard.org/standard/1_1final/dictionary/

@dirkschumacher has created a package for this: https://github.com/dirkschumacher/rhxl, but it needs expanding.

**Comment by dirkschumacher** [comment]
It should also have accessor functions for standard columns:

* date of onset
* date of report
* date of x where x in {death, hospitalization, ...}
* sex
* age
* age group
* a function that determines which concepts are available
* arbitrary query function based on HXL?

**Comment by dirkschumacher** [comment]
Convert a data frame to a linelist via `as_linelist`

**Comment by zkamvar** [comment]
Most of these concepts were implemented in the epiflows package with the `global_vars()`: https://www.repidemicsconsortium.org/epiflows/reference/global_vars.html

This allowed for flexibility of metadata stored with the data set so that it could be expanded.

**Comment by dirkschumacher** [comment]
Really nice

**Comment by zkamvar** [comment]
😊

**Comment by zkamvar** [comment]
I might take a page out of your book and use a data frame for the metadata.

**Comment by zkamvar** [comment]
I've got a skeleton of the structure up on the add-class branch.

**Comment by zkamvar** [comment]
What I'm envisioning is that the data structure will have an "epivars" attribute that is a list of the variables defined in the global "linelist.epivars". 

Each element in the epivars list represents a single variable: date of onset, gender, etc. It will be structured like so:

```
$date_onset
 ..$name: "onset"
 ..$hxl: "#date +start"
 ..$description: "Self-reported date of onset"
$id
 ..$name: "ID"
$geo
 ..$name: "lon" "lat"
 ..$hxl: "#geo +lon" "#geo +lat"
```

when you use the accessor, it immediately gives you the values from the column defined in the `$name` element.

I'm thinking of adding a `$` and `[[` method to allow for these attributes to be accessed in a standard way so that: `date_of_onset(x)` and `x$date_of_onset` both work.

**Comment by zkamvar** [comment]
Also, at this moment, it's VERY prototypical.... there are no tests and only limited documentation, but feedback welcome as always! https://github.com/reconhub/linelist/tree/add-class

**Comment by dirkschumacher** [comment]
I like the approach. I am not so sure about `x$date_of_onset` though, as it might confuse people thinking it is a standard data.frame.

How would you handle multiple columns in `geo`?

**Comment by zkamvar** [comment]
>  I am not so sure about x$date_of_onset though, as it might confuse people thinking it is a standard data.frame.
>
> How would you handle multiple columns in geo?

That's a good point. It would get kind of weird when you have `df$geo` always returning a data frame. In the *epicontacts* package, there are currently two ways of handling the data returned by the accessors:

1. as a data frame (with our without a second ID column)
2. as a vector

For the geo, if the second option is chosen, then the vector is returned as a matrix.

**Comment by thibautjombart** [comment]
This is pretty cool! :) 
@zkamvar It would be good to have a documented mechanism for changing the dictionary, i.e. a `set_meta` which would work like `set_epivars()` /  `set_epivars() <-`

**Comment by zkamvar** [comment]
Closing this and moving it to #18
