### ISSUE TITLE
custom print for linelist objects

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/linelist#25]
Ideally we could display the epivars as a sub-header to the variable names when printing the objects. In practice, this might be a little hell to do, so not sure if it will be worth it. But we could hope for something along the lines of :

```
> x
<linelist object>

       id date_of_onset  discharge   gender epi_case_definition messy_dates
     [id]                          [gender]
1  vwscyb    2018-01-06 2018-01-16     male           confirmed        <NA>
2  rzvrkm    2018-01-04 2018-01-14     male            probable  2018-10-19
3  hjcjyo    2018-01-10 2018-01-20     male           suspected        <NA>
4  ourjez    2018-01-03 2018-01-13   female           suspected  1989-12-24

```

**Comment by zkamvar** [comment]
I’ll take a look at this. I think the pillar package might have a solution given that it’s what makes the tibbles look pretty.
