### ISSUE TITLE
break off linelist class into its own package

### ISSUE THREAD

**Issue by zkamvar** [reconhub/linelist#29]
The package currently is split into two themes: implementing data cleaning and a data dictionary. The data dictionary part is fairly lightweight and has the potential for use outside of linelists. The data cleaning part, on the other hand, currently already requires the *stringi* package (via epitrix) and duplicates the effort of packages like janitor and lubridate. 

For example, while the `guess_date()` function works for dates like `"  24/11/84?"`, it will fail with `"  11/24/84"`. Lubridate has the `parse_date_time()` function for this purpose so that we don't have to deal with regexes like `"(0|1(?=[0-2]))[0-9]"` and `"([0-2]|3(?=[0-1]))[0-9]"` (representing months, and days, respectively) Moreso, #6 is [directly addressed by janitor's `excel_numeric_to_date()`](https://cran.r-project.org/web/packages/janitor/vignettes/janitor.html#fix-dates-stored-as-serial-numbers-with-excel_numeric_to_date). 

I think it may be worth adding both `lubridate` and `janitor` to the imports of linelist and splitting the class off into a separate package.

**Comment by thibautjombart** [comment]
Works for me, with the following caveats:

- make sure we have plenty enough coverage to pass it over to `lubridate` and `janitor`, making sure we don't loose functionality; at the time of development `guess_dates` was handling some dates that `lubridate` did not, but I think it has changed (stuff with weird characters and text surrounding the date)

- externalise the dictionary part as something more generic (?), e.g. `metadata`, or `metadf`?

- keep *linelist* as essentially a wrapper around these things

**Important**: *linelist* is currently used in our data pipelines, so we cannot have any breakdown of backward compatibility
