### ISSUE TITLE
dictionary based cleaning for variables

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/linelist#36]
A lot of variable cleaning boils down to replacing labels using a dictionary, along the lines of `dplyr::recode` and  `dplyr::recode_factor`. It would be nice to be able to:

- provide a dictionary for replacement as a 2 columns matrix or data.frame:
```
old_spelling    new_spelling
foubar      foobar
fubar       foobar
fobur       foobar
NA         unknown
missing    unknown 
```

- create a new function `clean_spelling(x, dictionary)` where `x` is a variable to clean
- create a new function `clean_variables(x, ...)` which runs `clean_variable_labels()` and `clean_spelling` on all `characters` and `factors`, where `...` is a named list of dictionaries
- add `clean_variables()` to `clean_data()`

Totally fine to use `dplyr::recode` and/or `case_when` under the hood if you want.

**Comment by zkamvar** [comment]
I'm thinking about creating the following:

 - [x] `clean_spelling()` acts on a vector
 - [x] `clean_variable_spelling()` applies `clean_spelling()` to a data frame
 - [x] `clean_variables()` applies `clean_variable_spelling()` and `clean_variable_labels()` to a data frame

I was initially confused as to why you wanted `clean_variables()`, but I now understand that it's a top-level variable cleaner without worrying about dates.

**Comment by thibautjombart** [comment]
"Great minds think alike. "

Ours too... ;)

**Comment by thibautjombart** [comment]
Note: the replacement of `NAs`  is an important point. It's quite good to be able to recode these, e.g. `NA = unknown` as sometimes we need to report missing entries, and e.g. `dplyr::filter(foo == "bar")` will obnoxiously drop NAs without warnings (just got bit by that one).

**Comment by zkamvar** [comment]
I'm currently working on the application to the full data.

There are a few things that the user will want/have

1. global data dictionary that the user wants to apply to their columns indiscriminately
2. dictionary in one data frame with a grouping column (any maybe a within-group sort-order column).
3. dictionary in a list of data frames

From my work on https://github.com/R4EPI/sitrep, the MSF dictionary has option 2, so I'm working on implementing flexibility for all of these.

**Comment by thibautjombart** [comment]
I'm not 100% sure I understand. Do you mean:

1. a big general dictionary
2. and 3. address the case where cleaning rules are variable-dependent, where 3. is the result of `split(dictionary_2, grouping_factor)

**Comment by zkamvar** [comment]
Yeah, pretty much.

**Comment by zkamvar** [comment]
I'm going to call it a day for today. I'll work a bit more on this tomorrow.

Currently, I've implemented `clean_spelling()` and `clean_variable_spelling()` and lost about an hour tracking down a weird issue with factor reordering that apparently only happens on my machine 😩 

These are all over on the cleaning-dictionary branch. Tomorrow, I'll be able to add a few more tests and insert it into the `clean_data()` function.

**Comment by zkamvar** [comment]
One thing I've run into that will be a useful check:

some dictionaries will define numeric codes, so if the user has a global dictionary without groups that has these numeric codes, they should be prevented from doing that.

**Comment by zkamvar** [comment]
> One thing I've run into that will be a useful check:
> 
> some dictionaries will define numeric codes, so if the user has a global dictionary without groups that has these numeric codes, they should be prevented from doing that.

I... have no clue what I meant by this 😳

**Comment by thibautjombart** [comment]
Hahaha. Nice! Coz I read it and thought "sure... I have no clue what he means". Could to see when I'm confused by what you write, so you are :joy_cat:

**Comment by thibautjombart** [comment]
Just posted a review for the PR. Awesome work all in all. Question, maybe worth adding to the current PR if the code overhead is small: it'd be good to have a *default* replacement. I appreciate this is aggressive behaviour, especially when applied to a whole `data.frame`, so shouldn't be a default. But this could be quite powereful. A way to indicate it could be:
```
old_spelling    new_spelling
foubar          foobar
fubar           foobar
fobur           foobar
NA              unknown
missing         unknown
.default        other
```

**Comment by thibautjombart** [comment]
Getting this further into awesomeness, some other features that would be awesome to have:

- [ ] allow variable names of the *wordlist* (currently `group`) to represent several variables, e.g. pipe-separated, or using regexp (in which case we may need a `regexp` argument to swtich that off if needed); e.g.

```
old_spelling    new_spelling    variable
foubar          foobar          first_name|last_name
fubar           foobar          first_name|last_name
fobur           foobar          first_name|last_name
NA              unknown         first_name|last_name|status
missing         unknown         status
.default        other           status
```

- [x] allows a wildcard in the variable names indicator to match any variable, e.g. `.all`

Happy to hear your thoughts on this. If you feel this belongs to a different issue feel free to repost.

**Comment by zkamvar** [comment]
I think the `.default` is quite doable (and a good idea), but the regex/pipe will take a *bit* more work, so I would appreciate the regex/pipe in a separate issue :)

**Comment by zkamvar** [comment]
I also think `.all/.global` is also quite doable, so I'll also work on that
