### ISSUE TITLE
guess_dates broken

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/linelist#42]
After merging the recent dictionary branch, I realised this no longer works:

```r
> guess_dates("example_data_2019-02-16.xlsx")
[1] "example_data_2019-02-16.xlsx"
```

Where the expected output is `2019-02-06`. This is used in current pipelines so needs urgent fixing. My bad for not having had a test for this (thought I did).

When I started developing this there were some cases `lubridate` didn't handle, which `guess_dates` did. Hopefully this is no longer the case.

**Comment by zkamvar** [comment]
Good thing you caught this! I've opened an issue in lubridate: https://github.com/tidyverse/lubridate/issues/752

I will re-instate the Thibaut rules as a supplement to catch what lubridate leaves behind. 

Sorry for the hiccup. You and I both know that parsing dates is a h\*cking nightmare. I'll fix this and add some tests to make sure it works.

**Comment by zkamvar** [comment]
For my own future reference:

It's pretty easy to restore a file deleted in git. I just found the commit that occurred right before I deleted them and checked out the files from there:

```
git checkout 35a8830 R/i_find_date_format.R
git checkout 35a8830 R/i_find_date_string.R
```

**Comment by zkamvar** [comment]
Also, because of the way I re-wrote the date-parsing function, it's not too difficult to drop in @thibautjombart's parsers :)
