### ISSUE TITLE
Cleaning dates which are numeric since 1900-01-01

### ISSUE THREAD

**Issue by samclifford** [reconhub/linelist#6]
One of the fruitier ways that dates/date-times get stored in Excel (or by users deliberately) is the number of days since 1900-01-01. While `as.Date()` can handle this, is there a way to check if a column which may have "date" or "time" in the title is a candidate for conversion from numeric?

**Comment by thibautjombart** [comment]
I think this is currently sorted, cf example:

```r
x <- c("43500", "toto", "2019-01-13", "4 feb 2010")
#> linelist::guess_dates(x, error_tolerance = 1)
#[1] "2019-02-04" NA           "2019-01-13" "2010-02-04"
```
