### ISSUE TITLE
Cleaning dates that also include a time stamp

### ISSUE THREAD

**Issue by pbkeating** [reconhub/linelist#69]
Hi @zkamvar 

Some colleagues here having to manage date variables that include a mixture of formats e.g. some regular dates dd-mm-yyyy and others with dd-mm-yyyy hh:mm:ss. Usually due to having people manually add dates (only dates) to excel sheets where the standard format is dates with timestamps.

Would it be possible to include in the clean_dates() function the ability to identify the dd-mm-yyyy with timestamps as regular dates also i.e. to remove the timestamps from them?

Let me know if that's clear.
Thanks,
P

**Comment by zkamvar** [comment]
Hi @pbkeating,

This is already possible, see the examples in https://www.repidemicsconsortium.org/linelist/reference/guess_dates.html

**Comment by pbkeating** [comment]
Thanks, Zhian.
A colleague here will send through an example of problems she had with mixed formats that clean_dates() didn't seem to clean.

P

**Comment by zkamvar** [comment]
> Thanks, Zhian.
> A colleague here will send through an example of problems she had with mixed formats that clean_dates() didn't seem to clean.
> 
> P

I'm assuming then that these are a different issue and will close this
