### ISSUE TITLE
top_values does not work with 2 categories and n = 1

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/linelist#91]
At 58ed4c745ef6ee4799e0912a5704a1176c084db2, we have:

```r
top_values(factor(c(1,1,2)), n = 1)
# [1] 1 1 2
# Levels: 1 2
``` 
while we would expect:
```r
# [1] 1 1 other
# Levels: 1 other
```

**Comment by zkamvar** [comment]
closing this in favor of #88 because it is described there.

**Comment by zkamvar** [comment]
https://github.com/reconhub/linelist/pull/90#issuecomment-534459911

**Comment by thibautjombart** [comment]
Thanks for the fix!
